jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        cache: maven
        distribution: adopt-hotspot
        java-version: '8'
    - continue-on-error: true
      name: Test with Maven
      run: mvn clean install -DskipTests -Dmaven.javadoc.skip=true -B -U && sh ./check_format.sh
        && mvn test
    - continue-on-error: true
      name: Codecov
      uses: codecov/codecov-action@v3.1.4
name: Test for linux
on:
  repository_dispatch:
    types: trigger-ga___linux_unit_test.yml
